'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Section = 'overview' | 'users' | 'transactions' | 'games' | 'rewards' | 'withdrawals'
type Row = Record<string, any>
type Data = { users: Row[]; transactions: Row[]; plays: Row[]; redemptions: Row[]; rewards: Row[]; giftCards: Row[] }
const empty: Data = { users: [], transactions: [], plays: [], redemptions: [], rewards: [], giftCards: [] }
const nav: Array<[Section, string]> = [['overview', 'Overview'], ['users', 'Users'], ['transactions', 'Transactions'], ['games', 'Game plays'], ['rewards', 'Rewards'], ['withdrawals', 'Withdrawals']]

export default function AdminPage() {
  const [session, setSession] = useState<any>(null)
  const [mode, setMode] = useState<'login' | 'signup' | 'forgot' | 'reset'>('login')
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState('')
  const [section, setSection] = useState<Section>('overview'); const [data, setData] = useState<Data>(empty); const [loading, setLoading] = useState(false)

  async function load(current = session) {
    if (!current) return
    setLoading(true)
    const response = await fetch('/api/admin', { method: 'POST', headers: { authorization: `Bearer ${current.access_token}`, 'content-type': 'application/json' }, body: JSON.stringify({ action: 'overview' }) })
    const result = await response.json(); setLoading(false)
    if (result.data) setData(result.data); if (result.error) setMessage(result.error)
  }
  useEffect(() => { const client = supabase(); client.auth.getSession().then(({ data: value }) => { setSession(value.session); if (value.session) load(value.session) }); const listener = client.auth.onAuthStateChange((_event, value) => { setSession(value); if (value) load(value) }); return () => listener.data.subscription.unsubscribe() }, [])

  async function auth(event: React.FormEvent) {
    event.preventDefault(); setMessage('')
    if (mode === 'forgot') { const { error } = await supabase().auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/` }); setMessage(error?.message ?? 'Check your email for a reset link.'); return }
    if (mode === 'reset') { if (password.length < 8 || password !== confirm) return setMessage('Use matching passwords with at least 8 characters.'); const { error } = await supabase().auth.updateUser({ password }); if (error) return setMessage(error.message); setMode('login'); setMessage('Password updated. Sign in.'); return }
    if (mode === 'signup' && password !== confirm) return setMessage('Passwords do not match.')
    const result = mode === 'signup' ? await supabase().auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth/callback` } }) : await supabase().auth.signInWithPassword({ email, password })
    if (result.error) return setMessage(result.error.message); if (result.data.session) { setSession(result.data.session); load(result.data.session) } else setMessage(mode === 'signup' ? 'Account created. Confirm your email, then sign in.' : 'No active session returned. Confirm your email or request a new reset link.')
  }
  async function call(body: Record<string, unknown>) { if (!session) return; const response = await fetch('/api/admin', { method: 'POST', headers: { authorization: `Bearer ${session.access_token}`, 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); setMessage(result.error ?? 'Saved.'); if (!result.error) load() }
  const current = section === 'users' ? data.users : section === 'transactions' ? data.transactions : section === 'games' ? data.plays : section === 'rewards' ? data.rewards : data.redemptions
  const stats = useMemo(() => ({ users: data.users.length, coins: data.users.reduce((sum, user) => sum + Number(user.balance || 0), 0), pending: data.redemptions.filter((row) => row.status === 'pending').length, plays: data.plays.length }), [data])

  if (!session) return <main className="auth-shell"><section className="auth-card"><p className="eyebrow">L Rewards / Operations</p><h1>{mode === 'signup' ? 'Create account' : mode === 'forgot' ? 'Reset password' : mode === 'reset' ? 'Choose a new password' : 'Admin sign in'}</h1><p className="muted">Real-time control center for the Android rewards app.</p><form onSubmit={auth}>{mode !== 'reset' && <input type="email" placeholder="Email address" value={email} onChange={(event) => setEmail(event.target.value)} required />}{mode !== 'forgot' && <input type="password" placeholder={mode === 'reset' ? 'New password' : 'Password'} minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} required />}{(mode === 'signup' || mode === 'reset') && <input type="password" placeholder="Confirm password" minLength={8} value={confirm} onChange={(event) => setConfirm(event.target.value)} required />}<button>{mode === 'signup' ? 'Create account' : mode === 'forgot' ? 'Email reset link' : mode === 'reset' ? 'Save new password' : 'Sign in'}</button></form><div className="auth-links"><button className="link-button" onClick={() => setMode(mode === 'signup' ? 'login' : 'signup')}>{mode === 'signup' ? 'Back to sign in' : 'Create account'}</button><button className="link-button" onClick={() => setMode(mode === 'forgot' ? 'login' : 'forgot')}>{mode === 'forgot' ? 'Back to sign in' : 'Forgot password?'}</button></div>{message && <p className="message">{message}</p>}</section></main>

  return <main className="app-shell"><aside><div className="brand"><span className="brand-mark">L</span><div><strong>L Rewards</strong><small>Live control center</small></div></div><nav>{nav.map(([key, label]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => setSection(key)}>{label}</button>)}</nav><button className="signout" onClick={() => supabase().auth.signOut()}>Sign out</button></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">Supabase live data</p><h1>{nav.find(([key]) => key === section)?.[1]}</h1></div><button className="secondary" onClick={() => load()}>{loading ? 'Refreshing…' : 'Refresh'}</button></header>{section === 'overview' ? <><div className="stats"><Metric label="Users" value={stats.users} /><Metric label="Coins in circulation" value={stats.coins} /><Metric label="Pending withdrawals" value={stats.pending} /><Metric label="Game plays" value={stats.plays} /></div><div className="panel-grid"><Panel title="Latest withdrawals"><Table rows={data.redemptions.slice(0, 8)} fields={['user_email', 'reward', 'cost', 'status']} /></Panel><Panel title="Latest activity"><Table rows={data.transactions.slice(0, 8)} fields={['user_email', 'game_type', 'amount', 'created_at']} /></Panel></div></> : <Panel title={`${nav.find(([key]) => key === section)?.[1]} · ${current.length} live records`}>{section === 'users' && <UserTable rows={current} onAdjust={(user) => { const amount = Number(window.prompt(`Coin adjustment for ${user.email}. Use negative to remove coins.`)); const note = window.prompt('Reason for this adjustment'); if (Number.isInteger(amount) && note) call({ action: 'adjust_balance', userId: user.id, amount, note }) }} />}{section === 'withdrawals' && <WithdrawalTable rows={current} onUpdate={(row, status) => { const note = window.prompt('Admin note or payment reference', row.admin_note ?? ''); if (note !== null) call({ action: 'update_withdrawal', id: row.id, status, adminNote: note }) }} />}{section === 'rewards' && <Table rows={current} fields={['label', 'type', 'cost', 'active']} action={(row) => call({ action: 'update_reward', id: row.id, active: !row.active })} actionLabel="Toggle active" />}{(section === 'transactions' || section === 'games') && <Table rows={current} fields={section === 'games' ? ['user_email', 'game_type', 'reward_amount', 'created_at'] : ['user_email', 'game_type', 'amount', 'created_at']} />}</Panel>}{message && <p className="message">{message}</p>}</section></main>
}
function Metric({ label, value }: { label: string; value: number }) { return <article className="metric"><span>{label}</span><strong>{value.toLocaleString()}</strong></article> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><div className="panel-heading"><h2>{title}</h2></div>{children}</section> }
function Table({ rows, fields, action, actionLabel = 'Action' }: { rows: Row[]; fields: string[]; action?: (row: Row) => void; actionLabel?: string }) { return <div className="table-wrap"><table><thead><tr>{fields.map((field) => <th key={field}>{field.replaceAll('_', ' ')}</th>)}{action && <th>{actionLabel}</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.id ?? index}>{fields.map((field) => <td key={field}>{field === 'created_at' ? new Date(row[field]).toLocaleString() : String(row[field] ?? '—')}</td>)}{action && <td><button className="table-action" onClick={() => action(row)}>{actionLabel}</button></td>}</tr>)}</tbody></table>{!rows.length && <p className="empty">No live records found.</p>}</div> }
function UserTable({ rows, onAdjust }: { rows: Row[]; onAdjust: (row: Row) => void }) { return <Table rows={rows} fields={['email', 'balance', 'transactions', 'plays', 'redemptions', 'confirmed']} action={onAdjust} actionLabel="Adjust coins" /> }
function WithdrawalTable({ rows, onUpdate }: { rows: Row[]; onUpdate: (row: Row, status: string) => void }) { return <Table rows={rows.map((row) => ({ ...row, value: `₹${Number(row.value_inr ?? Number(row.cost ?? 0) / 100).toFixed(0)}` }))} fields={['user_email', 'reward', 'value', 'destination', 'status', 'admin_note']} action={(row) => onUpdate(row, row.status === 'pending' ? 'approved' : row.status === 'approved' ? 'paid' : 'rejected')} actionLabel="Advance status" /> }
